@ECHO OFF
:: This will setup the computer's name on a folder that can be pinned to the taskbar.
:: Created by Hugh Smalley
IF EXIST "%USERPROFILE%\%COMPUTERNAME%" GOTO DONE
IF NOT EXIST "%USERPROFILE%\%COMPUTERNAME%" GOTO SETUP
:ERROR
ECHO YOU SHOULD NEVER SEE THS
ECHO THIS IS AN ERROR
:SETUP
MKDIR "%USERPROFILE%\%COMPUTERNAME%"
:DONE
ECHO COMPUTER NAME FOLDER IS "%USERPROFILE%\%COMPUTERNAME%"
EXIT