@ECHO OFF
::	POWER PROFILE CONFIG
::		SEE: http://www.energystar.gov/index.cfm?c=power_mgt.pr_power_mgt_powerconfig
:: MAKE SURE ADMIN ACCOUNTS DO NOT SET POWER OPTIONS ON SERVERS
IF %USERNAME% == ADMINYMIN GOTO END
IF %USERNAME% == SAMSHAMIN GOTO END
:: FIND OUT WHAT OS
IF EXIST %SYSTEMDRIVE%\USERS GOTO WIN7
IF NOT EXIST %SYSTEMDRIVE%\USERS GOTO WINXP
GOTO ERROR
:ERROR
::	ERROR SCREEN
ECHO THIS IS AN ERROR SCREEN YOU SHOULD NEVER SEE IT
ECHO FEEL FREE TO PANIC NOW
GOTO END
GOTO ERROR
:WINXP
::	SETS WINDOWS XP POWER OPTIONS
:: CREATE CUSTOM PROFILE
POWERCFG /CREATE LUA
:: SET MONITOR TIMEOUTS
POWERCFG /CHANGE LUA /MONITOR-TIMEOUT-AC 15
POWERCFG /CHANGE LUA /MONITOR-TIMEOUT-DC 15
:: SET DISK TIMEOUTS
POWERCFG /CHANGE LUA /DISK-TIMEOUT-AC 15
POWERCFG /CHANGE LUA /DISK-TIMEOUT-DC 15
:: SET STANDBY TIMEOUTS
POWERCFG /CHANGE LUA /STANDBY-TIMEOUT-AC 0
POWERCFG /CHANGE LUA /STANDBY-TIMEOUT-DC 60
:: DISABLE HIBERNATION IN PROFILE
POWERCFG /CHANGE LUA /HIBERNATE-TIMEOUT-AC 0
POWERCFG /CHANGE LUA /HIBERNATE-TIMEOUT-DC 0
:: TELL CPU TO NOT LIMIT THE PROCESSOR
POWERCFG /CHANGE LUA /PROCESSOR-THROTTLE-AC ADAPTIVE
POWERCFG /CHANGE LUA /PROCESSOR-THROTTLE-DC ADAPTIVE
:: ACTIVATE CUSTOM PROFILE
POWERCFG /SETACTIVE LUA
:: DISABLE HIBERATION
POWERCFG /HIBERNATE OFF
:: SET VIDEO DIM ON BATTERY TO CONSERVE POWER
POWERCFG /GLOBALPOWERFLAG ON /OPTION VIDEODIM
:: SETUP BATTERY ALARMS
POWERCFG /BATTERYALARM LOW /ACTIVATE ON
POWERCFG /BATTERYALARM CRITICAL /ACTIVATE ON
:: AT 25% ALERT USER OF LOW BATTERY
:: AT 5% ALERT USER OF CRITIAL BATTERY POWER
POWERCFG /BATTERYALARM LOW /LEVEL 25
POWERCFG /BATTERYALARM CRITICAL /LEVEL 5
POWERCFG /BATTERYALARM LOW /TEXT ON
POWERCFG /BATTERYALARM CRITICAL /TEXT ON
POWERCFG /BATTERYALARM LOW /SOUND OFF
POWERCFG /BATTERYALARM CRITICAL /SOUND ON
:: DO NOTHING ABOUT ABOUT THE ALARMS, LET USER TAKE ACTION
POWERCFG /BATTERYALARM LOW /ACTION NONE
POWERCFG /BATTERYALARM CRITICAL /ACTION NONE
GOTO END
GOTO ERROR
:WIN7
::	SETS WINDOWS 8 POWER OPTIONS
:: CHANGE POWER OPTIONS TO MAX SAVINGS
POWERCFG -SETACTIVE SCHEME_MAX
:: ENABLE HIBERNATE
POWERCFG -HIBERNATE ON
:: SET MONITOR TIMEOUTS
POWERCFG -CHANGE -MONITOR-TIMEOUT-AC 15
POWERCFG -CHANGE -MONITOR-TIMEOUT-DC 15
:: SET DISK TIMEOUTS
POWERCFG -CHANGE -DISK-TIMEOUT-AC 15
POWERCFG -CHANGE -DISK-TIMEOUT-DC 15
:: SET STANDBY TIMEOUTS
POWERCFG -CHANGE -STANDBY-TIMEOUT-AC 0
POWERCFG -CHANGE -STANDBY-TIMEOUT-DC 60
:: SET HIBERANTE TIMEOUT / DISABLE ON AC
POWERCFG -CHANGE -HIBERNATE-TIMEOUT-AC 0
POWERCFG -CHANGE -HIBERNATE-TIMEOUT-DC 120
GOTO END
GOTO ERROR
:END
:: SET LOGON SCREEN TIMEOUTS
REG ADD "HKU\.DEFAULT\Control Panel\Desktop" /v PowerOffActive /t REG_SZ /d 1 /f
REG ADD "HKU\.DEFAULT\Control Panel\Desktop" /v ScreenSaveActive /t REG_SZ /d 1 /f
GOTO EOF
GOTO ERROR
:EOF