@ECHO OFF
CLS
ECHO.
ECHO THIS SCRIPT WILL TURN OFF SERVICES AND KILL PROCESSES
ECHO THIS WILL INCREASE PERFORMACE AT THE RISK OF DISABLING SECURITY AND NETWORK SHARING
ECHO YOU WILL NEED TO RESTART TO RESTORE SYSTEM STATE
ECHO EXIT NOW OR ABANDON ALL YE HOPE.
PAUSE > NUL

ECHO Turning Off Memory and CPU Consuming Services.
NET STOP BFE
NET STOP LanmanWorkstation
NET STOP WPDBusEnum
NET STOP HomeGroupProvider
NET STOP Browser
NET STOP fdPHost
NET STOP WdiServiceHost
NET STOP AeLookupSvc
NET STOP UxSms
NET STOP PcaSvc
NET STOP TrkWks
NET STOP lmhosts
NET STOP DPS
NET STOP WSearch
NET STOP WMPNetworkSvc
NET STOP vds
NET STOP SDRSVC
ECHO Security
NET STOP MsMpSvc
NET STOP MpsSvc
NET STOP wuauserv
ECHO Misc Things
NET STOP Mongoose 2.8
NET STOP LMIMaint
NET STOP LogMeIn
ECHO KILLING PROCESS
REM TSKILL MAGICJACK
TSKILL MONGOOSE
TSKILL DROPBOX
TSKILL GOOGLEUPDATE
TSKILL ehsched
TSKILL ehrecvr
TSKILL VDS
TSKILL NTUNESERVICE
TSKILL NTUNECMD
TSKILL UPDATECENTERSERVICE
TSKILL GoogleCrashHandler
TSKILL Deskcretary
TSKILL FusionSVC
ECHO EMPTY TEMP FILES
DEL /Q /S %TEMP%\ > NUL